# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_dialog_end_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialog',
            name='end_utterance',
            field=models.TextField(default=''),
        ),
    ]
