# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_dialog_end_utterance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='node',
            name='allowed_intents',
            field=models.ManyToManyField(to='chatbot.Intent'),
        ),
    ]
