# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_auto_20171206_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='next_nodes',
            field=models.ManyToManyField(blank=True, to='chatbot.Node'),
        ),
        migrations.AlterField(
            model_name='node',
            name='allowed_intents',
            field=models.ManyToManyField(blank=True, to='chatbot.Intent'),
        ),
    ]
