# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_entity'),
    ]

    operations = [
        migrations.CreateModel(
            name='chatbot_utterance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatbot_template', models.TextField(default='')),
                ('entities', models.ManyToManyField(blank=True, to='chatbot.Entity')),
            ],
        ),
        migrations.RenameField(
            model_name='node',
            old_name='chatbot_utternace',
            new_name='chatbot_utterance',
        ),
    ]
