# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_auto_20171207_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='chatbot_utterance',
        ),
        migrations.AddField(
            model_name='node',
            name='chatbot_utterance',
            field=models.ManyToManyField(to='chatbot.chatbot_utterance'),
        ),
    ]
