# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 02:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0009_auto_20171207_0049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dialog',
            old_name='end_node',
            new_name='practice_node',
        ),
    ]
