# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0010_auto_20171208_0210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hint', models.TextField(default='')),
                ('answer', models.TextField(default='')),
            ],
        ),
    ]
