# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 02:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0011_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot.Quiz'),
        ),
    ]
